name: Build app
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: npm install
      - name: Build Webapp
        run:  npm run build
      - name: List /build
        run: ls ./build
